# Generated by Django 4.0.4 on 2022-07-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time',
            new_name='timeDb',
        ),
    ]
