# Generated by Django 4.0.4 on 2022-07-26 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_time_timedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedb',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
