# Generated by Django 4.0.4 on 2022-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_timedb_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedb',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timedb',
            name='startedtime',
            field=models.TimeField(),
        ),
    ]
