# Generated by Django 4.0.4 on 2022-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_timedb_endtime_alter_timedb_startedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedb',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timedb',
            name='startedtime',
            field=models.DateTimeField(),
        ),
    ]
