# Generated by Django 4.0.4 on 2022-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_timedb_endtime_alter_timedb_startedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchperdayDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100)),
            ],
        ),
    ]
